### ISSUE TITLE
UnboundLocalError: local variable 'devid' referenced before assignment

### ISSUE THREAD

**Issue by jmbrederveld** [roysjosh/nanoleaf-ltpdu#2]
Hi Joshua,

I am attempting to control several Nanoleaf devices (Lightbulb A19 and Essentials Lightstrip) over Thread using a HomePod Mini.
Both are paired in the Home app on my iOS device.

Running `avahi-browse -v -t -l -r -p _ltpdu._udp` I can see the devices and their respective IPv6 addresses in my network.

Next, I am running the `nlctl.py` script to communicate with one of the devices like follows:
`python nlctl.py --devices <4 char dev ID> auth=<home kit setup code> --zeroconf-timeout 30`

This results in the following exception:

```
Traceback (most recent call last):
  File "/home/jmbrederveld/Developer/nanoleaf-ltpdu/nlctl.py", line 337, in <module>
    asyncio.get_event_loop().run_until_complete(amain(args))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jmbrederveld/Developer/nanoleaf-ltpdu/nlctl.py", line 301, in amain
    print("No matching devices for action %s@%s" % (action, devid))
UnboundLocalError: local variable 'devid' referenced before assignment
```
I had it working earlier, and could set power on/off, brightness, etc, but currently I can't seem to replicate the pairing procedure to get the authentication context..

Any idea on why this exception occurs, or how I can approach this problem?

Thank you in advance!

**Comment by roysjosh** [comment]
Hmm, I've hard coded anything of length 8 to be a pairing code and otherwise an access token so make sure you aren't putting the dashes in. Can you `ping6` this particular bulb, e.g. `ping6 Nanoleaf-A19-1234.local.`?

Let me pepper you with a few questions:
Is this a previously working bulb? Was it factory reset? Do you have just the one? Are any bulbs working?

Could you please show the avahi output plus the CLI command with only the PIN redacted? I'll probably have to add some debugging, too.

**Comment by jmbrederveld** [comment]
Thank you for your quick response.

I have reset the bulb several times, also tried different bulbs (since I have a pack of three). The same procedure with other bulbs result in the same error.

Interestingly, issuing `ping6 Nanoleaf-A19-2HKT.local` results in `ping6: Nanoleaf-A19-2HKT.local: Name or service not known`
But `ping6 fd1d:757f:7cc7:0:f575:9905:7439:1614` does work, so I guess this does indeed seem to relate to Zeroconf/mDNS.. 

Also, I can CoAP POST the (unencrypted) identify payload to the light bulb using the IP address directly just fine, the bulb starts flashing.

Here you can see the output which you requested:

`avahi-browse -v -t -l -r -p _ltpdu._udp`

```
+;enp0s31f6;IPv6;Nanoleaf\032A19\0322HKT;_ltpdu._udp;local
+;enp0s31f6;IPv6;Nanoleaf\032Strip\0329HSK;_ltpdu._udp;local
+;enp0s31f6;IPv4;Nanoleaf\032A19\0322HKT;_ltpdu._udp;local
+;enp0s31f6;IPv4;Nanoleaf\032Strip\0329HSK;_ltpdu._udp;local
=;enp0s31f6;IPv6;Nanoleaf\032Strip\0329HSK;_ltpdu._udp;local;Nanoleaf-Strip-9HSK.local;fd1d:757f:7cc7:0:4d0a:98aa:815a:71de;5683;"eui64=804B50FFFEEA43E1" "md=NL55" "srcvers=1.6.35" "id=0D:C2:F0:27:3E:C5\000"
=;enp0s31f6;IPv6;Nanoleaf\032A19\0322HKT;_ltpdu._udp;local;Nanoleaf-A19-2HKT.local;fd1d:757f:7cc7:0:f575:9905:7439:1614;5683;"eui64=9035EAFFFED1093B" "md=NL45" "srcvers=1.6.24" "id=48:9B:31:7A:E6:91\000"
=;enp0s31f6;IPv4;Nanoleaf\032Strip\0329HSK;_ltpdu._udp;local;Nanoleaf-Strip-9HSK.local;fd1d:757f:7cc7:0:4d0a:98aa:815a:71de;5683;"eui64=804B50FFFEEA43E1" "md=NL55" "srcvers=1.6.35" "id=0D:C2:F0:27:3E:C5\000"
=;enp0s31f6;IPv4;Nanoleaf\032A19\0322HKT;_ltpdu._udp;local;Nanoleaf-A19-2HKT.local;fd1d:757f:7cc7:0:f575:9905:7439:1614;5683;"eui64=9035EAFFFED1093B" "md=NL45" "srcvers=1.6.24" "id=48:9B:31:7A:E6:91\000"
```

In `nlctl.py` I have set the log levels as follows:

```
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('zeroconf').setLevel(logging.DEBUG)
```

`python nlctl.py --devices 2HKT auth=XXXXXXXX` 

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:zeroconf:Creating new socket with port 5353, ip_version IPVersion.V6Only, apple_p2p False and bind_addr ('',)
DEBUG:zeroconf:Created socket <socket.socket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 5353, 0, 0)>
DEBUG:zeroconf:Adding (('fe80::4a71:bfa2:7ae5:65f7', 0, 2), 2) (socket 7) to multicast group
DEBUG:zeroconf:Creating new socket with port 5353, ip_version IPVersion.V6Only, apple_p2p False and bind_addr ('fe80::4a71:bfa2:7ae5:65f7', 0, 2)
DEBUG:zeroconf:Created socket <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('fe80::4a71:bfa2:7ae5:65f7', 5353, 0, 2)>
DEBUG:zeroconf:Configuring socket <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('fe80::4a71:bfa2:7ae5:65f7', 5353, 0, 2)> with multicast interface (('fe80::4a71:bfa2:7ae5:65f7', 0, 2), 2)
DEBUG:zeroconf:Adding (('fddd:ce7e:607f:4f25:f37b:60c9:de4b:e88c', 0, 0), 2) (socket 7) to multicast group
INFO:zeroconf:Address in use when adding (('fddd:ce7e:607f:4f25:f37b:60c9:de4b:e88c', 0, 0), 2) to multicast group, it is expected to happen on some systems
DEBUG:zeroconf:Adding (('::1', 0, 0), 1) (socket 7) to multicast group
DEBUG:zeroconf:Creating new socket with port 5353, ip_version IPVersion.V6Only, apple_p2p False and bind_addr ('::1', 0, 0)
DEBUG:zeroconf:Created socket <socket.socket fd=9, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 5353, 0, 0)>
DEBUG:zeroconf:Configuring socket <socket.socket fd=9, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 5353, 0, 0)> with multicast interface (('::1', 0, 0), 1)
DEBUG:zeroconf:Adding (('fddd:ce7e:607f:4f25:7469:2f72:3ba3:425d', 0, 0), 2) (socket 7) to multicast group
INFO:zeroconf:Address in use when adding (('fddd:ce7e:607f:4f25:7469:2f72:3ba3:425d', 0, 0), 2) to multicast group, it is expected to happen on some systems
DEBUG:zeroconf:Listen socket <socket.socket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 5353, 0, 0)>, respond sockets [<socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('fe80::4a71:bfa2:7ae5:65f7', 5353, 0, 2)>, <socket.socket fd=9, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 5353, 0, 0)>]
DEBUG:zeroconf:offsets = questions=0, answers=0, authorities=0, additionals=0
DEBUG:zeroconf:lengths = questions=1, answers=0, authorities=0, additionals=0
DEBUG:zeroconf:now offsets = questions=1, answers=0, authorities=0, additionals=0
DEBUG:zeroconf:Sending to (None, 5353) (35 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[ptr[question,QU,in,_ltpdu._udp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06_ltpdu\x04_udp\x05local\x00\x00\x0c\x80\x01'...
WARNING:zeroconf:Error with socket 9: [Errno 101] Network is unreachable
DEBUG:zeroconf:IPv6 scope_id 2 associated to the receiving interface
DEBUG:zeroconf:Received from 'fe80::4a71:bfa2:7ae5:65f7':5353 (socket 7): <DNSIncoming:{id=0, flags=0, truncated=False, n_q=1, n_ans=0, n_auth=0, n_add=0, questions=[ptr[question,QU,in,_ltpdu._udp.local.]], answers=[]}> (35 bytes) as [b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06_ltpdu\x04_udp\x05local\x00\x00\x0c\x80\x01']
DEBUG:zeroconf:offsets = questions=0, answers=0, authorities=0, additionals=0
DEBUG:zeroconf:lengths = questions=1, answers=0, authorities=0, additionals=0
DEBUG:zeroconf:now offsets = questions=1, answers=0, authorities=0, additionals=0
DEBUG:zeroconf:Sending to (None, 5353) (35 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[ptr[question,QM,in,_ltpdu._udp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06_ltpdu\x04_udp\x05local\x00\x00\x0c\x00\x01'...
DEBUG:zeroconf:Error with socket 9: [Errno 101] Network is unreachable
DEBUG:zeroconf:IPv6 scope_id 2 associated to the receiving interface
DEBUG:zeroconf:Received from 'fe80::4a71:bfa2:7ae5:65f7':5353 (socket 7): <DNSIncoming:{id=0, flags=0, truncated=False, n_q=1, n_ans=0, n_auth=0, n_add=0, questions=[ptr[question,QM,in,_ltpdu._udp.local.]], answers=[]}> (35 bytes) as [b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06_ltpdu\x04_udp\x05local\x00\x00\x0c\x00\x01']
Traceback (most recent call last):
  File "/home/jmbrederveld/Developer/nanoleaf-ltpdu/nlctl.py", line 337, in <module>
    asyncio.get_event_loop().run_until_complete(amain(args))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jmbrederveld/Developer/nanoleaf-ltpdu/nlctl.py", line 301, in amain
    print("No matching devices for action %s@%s" % (action, devid))
UnboundLocalError: local variable 'devid' referenced before assignment
```

Hopefully this information is sufficient, let me know if there's anything else I can do to give you more insight into this problem.

Thank you again!

**Comment by roysjosh** [comment]
Hmm. The `ping6` failing to resolve the address is concerning. Your logs show `Sending to (None, 5353) ...` while my logs show a proper multicast destination: `Sending to (ff02::fb, 5353) ...`. Do you see traffic on 5353 when running the `nlctl.py` script? `tcpdump -pevnni enp0s31f6 port 5353` as root based on your output above.

**Comment by roysjosh** [comment]
Well, reading your debug more closely I'll guess that you do. Socket 7 receives your query. Hmm. What about the output from `ip -6 maddr`? I hate to ask but have you tried restarting your computer, WiFi AP, and/or HomePod Mini?

**Comment by jmbrederveld** [comment]
Hello again!
I followed all your suggested steps, and turns out, it works now, like it did before!
No idea how or why- which is kind of unsatisfactory. 

All devices reset, rebooted, and it works consistently now.

I really have no clue how or why it suddenly started working. I suspect it is related to the HomePod mini.

Thank you again for your help! I will close this issue.
